-- geo_city_options: static catalog for location dropdowns (offline seed)
-- Apply in Supabase: SQL Editor or `supabase db push`

create table if not exists public.geo_city_options (
  id uuid primary key default gen_random_uuid(),
  country_or_region text not null,
  state_province text not null,
  city text not null,
  city_slug text not null,
  sort_order int not null default 0,
  constraint geo_city_options_city_slug_unique unique (city_slug)
);

create index if not exists geo_city_options_country_state_idx
  on public.geo_city_options (country_or_region, state_province);

alter table public.geo_city_options enable row level security;

drop policy if exists "geo_city_options_select_public" on public.geo_city_options;
create policy "geo_city_options_select_public"
  on public.geo_city_options
  for select
  to anon, authenticated
  using (true);

truncate public.geo_city_options restart identity;

insert into public.geo_city_options (country_or_region, state_province, city, city_slug, sort_order)
values
('United States','California','San Francisco','san-francisco',1),
('United States','California','Los Angeles','los-angeles',2),
('United States','California','San Diego','san-diego',3),
('United States','California','Palo Alto','palo-alto',4),
('United States','New York','New York','new-york',5),
('United States','New York','Buffalo','buffalo',6),
('United States','Illinois','Chicago','chicago',7),
('United States','Massachusetts','Boston','boston',8),
('United States','Washington','Seattle','seattle',9),
('United States','Washington','Bellevue','bellevue',10),
('United States','Texas','Austin','austin',11),
('United States','Texas','Dallas','dallas',12),
('United States','Texas','Houston','houston',13),
('United States','District of Columbia','Washington','washington-dc',14),
('United States','Georgia','Atlanta','atlanta',15),
('United States','Pennsylvania','Philadelphia','philadelphia',16),
('United States','Colorado','Denver','denver',17),
('United States','Florida','Miami','miami',18),
('United States','Florida','Orlando','orlando',19),
('Canada','Ontario','Toronto','toronto',20),
('Canada','Ontario','Ottawa','ottawa',21),
('Canada','British Columbia','Vancouver','vancouver',22),
('Canada','British Columbia','Victoria','victoria-bc',23),
('Canada','Quebec','Montreal','montreal',24),
('Canada','Alberta','Calgary','calgary',25),
('Canada','Alberta','Edmonton','edmonton',26),
('United Kingdom','England','London','london',27),
('United Kingdom','England','Manchester','manchester',28),
('United Kingdom','England','Birmingham','birmingham-uk',29),
('United Kingdom','England','Cambridge','cambridge-uk',30),
('United Kingdom','Scotland','Edinburgh','edinburgh',31),
('United Kingdom','Scotland','Glasgow','glasgow',32),
('United Kingdom','Wales','Cardiff','cardiff',33),
('United Kingdom','Northern Ireland','Belfast','belfast',34),
('France','Ile-de-France','Paris','paris',35),
('France','Auvergne-Rhone-Alpes','Lyon','lyon',36),
('France','Provence-Alpes-Cote d''Azur','Marseille','marseille',37),
('Germany','Berlin','Berlin','berlin',38),
('Germany','Bavaria','Munich','munich',39),
('Germany','Hamburg','Hamburg','hamburg',40),
('Germany','Hesse','Frankfurt','frankfurt',41),
('Netherlands','North Holland','Amsterdam','amsterdam',42),
('Netherlands','South Holland','Rotterdam','rotterdam',43),
('Netherlands','South Holland','The Hague','the-hague',44),
('Netherlands','North Brabant','Eindhoven','eindhoven',45),
('Switzerland','Zurich','Zurich','zurich',46),
('Switzerland','Geneva','Geneva','geneva',47),
('Switzerland','Basel-Stadt','Basel','basel',48),
('Spain','Community of Madrid','Madrid','madrid',49),
('Spain','Catalonia','Barcelona','barcelona',50),
('Spain','Andalusia','Seville','seville',51),
('Italy','Lombardy','Milan','milan',52),
('Italy','Lazio','Rome','rome',53),
('Italy','Piedmont','Turin','turin',54),
('Sweden','Stockholm County','Stockholm','stockholm',55),
('Sweden','Skane County','Malmo','malmo',56),
('Sweden','Vastra Gotaland','Gothenburg','gothenburg',57),
('Singapore','N/A','Singapore','singapore',58),
('Japan','Tokyo','Tokyo','tokyo',59),
('Japan','Kanagawa','Yokohama','yokohama',60),
('Japan','Osaka','Osaka','osaka',61),
('Japan','Aichi','Nagoya','nagoya',62),
('South Korea','Seoul','Seoul','seoul',63),
('South Korea','Busan','Busan','busan',64),
('South Korea','Incheon','Incheon','incheon',65),
('Hong Kong','N/A','Hong Kong','hong-kong',66),
('Taiwan','Taiwan','Taipei','taipei',67),
('Taiwan','Taiwan','Kaohsiung','kaohsiung',68),
('Taiwan','Taiwan','Taichung','taichung',69),
('United Arab Emirates','Dubai','Dubai','dubai',70),
('United Arab Emirates','Abu Dhabi','Abu Dhabi','abu-dhabi',71),
('India','Maharashtra','Mumbai','mumbai',72),
('India','Karnataka','Bengaluru','bengaluru',73),
('India','Delhi','New Delhi','new-delhi',74),
('India','Telangana','Hyderabad','hyderabad',75),
('Australia','New South Wales','Sydney','sydney',76),
('Australia','Victoria','Melbourne','melbourne',77),
('Australia','Queensland','Brisbane','brisbane',78),
('Australia','Western Australia','Perth','perth',79),
('China','Beijing','Beijing','beijing',80),
('China','Tianjin','Tianjin','tianjin',81),
('China','Shanghai','Shanghai','shanghai',82),
('China','Chongqing','Chongqing','chongqing',83),
('China','Hebei','Shijiazhuang','shijiazhuang',84),
('China','Hebei','Tangshan','tangshan',85),
('China','Hebei','Baoding','baoding',86),
('China','Shanxi','Taiyuan','taiyuan',87),
('China','Shanxi','Datong','datong',88),
('China','Liaoning','Shenyang','shenyang',89),
('China','Liaoning','Dalian','dalian',90),
('China','Jilin','Changchun','changchun',91),
('China','Jilin','Jilin City','jilin-city',92),
('China','Heilongjiang','Harbin','harbin',93),
('China','Heilongjiang','Daqing','daqing',94),
('China','Jiangsu','Nanjing','nanjing',95),
('China','Jiangsu','Suzhou','suzhou-cn',96),
('China','Jiangsu','Wuxi','wuxi',97),
('China','Zhejiang','Hangzhou','hangzhou',98),
('China','Zhejiang','Ningbo','ningbo',99),
('China','Zhejiang','Wenzhou','wenzhou',100),
('China','Anhui','Hefei','hefei',101),
('China','Anhui','Wuhu','wuhu',102),
('China','Fujian','Fuzhou','fuzhou-cn',103),
('China','Fujian','Xiamen','xiamen',104),
('China','Fujian','Quanzhou','quanzhou',105),
('China','Jiangxi','Nanchang','nanchang',106),
('China','Jiangxi','Ganzhou','ganzhou',107),
('China','Shandong','Jinan','jinan',108),
('China','Shandong','Qingdao','qingdao',109),
('China','Shandong','Yantai','yantai',110),
('China','Henan','Zhengzhou','zhengzhou',111),
('China','Henan','Luoyang','luoyang',112),
('China','Hubei','Wuhan','wuhan',113),
('China','Hubei','Yichang','yichang',114),
('China','Hunan','Changsha','changsha',115),
('China','Hunan','Zhuzhou','zhuzhou',116),
('China','Guangdong','Guangzhou','guangzhou',117),
('China','Guangdong','Shenzhen','shenzhen',118),
('China','Guangdong','Dongguan','dongguan',119),
('China','Guangdong','Foshan','foshan',120),
('China','Guangdong','Zhuhai','zhuhai',121),
('China','Hainan','Haikou','haikou',122),
('China','Hainan','Sanya','sanya',123),
('China','Sichuan','Chengdu','chengdu',124),
('China','Sichuan','Mianyang','mianyang',125),
('China','Guizhou','Guiyang','guiyang',126),
('China','Guizhou','Zunyi','zunyi',127),
('China','Yunnan','Kunming','kunming',128),
('China','Yunnan','Dali','dali-cn',129),
('China','Shaanxi','Xi''an','xian-cn',130),
('China','Shaanxi','Xianyang','xianyang',131),
('China','Gansu','Lanzhou','lanzhou',132),
('China','Qinghai','Xining','xining',133),
('China','Guangxi','Nanning','nanning',134),
('China','Guangxi','Guilin','guilin',135),
('China','Inner Mongolia','Hohhot','hohhot',136),
('China','Inner Mongolia','Baotou','baotou',137),
('China','Ningxia','Yinchuan','yinchuan',138),
('China','Xinjiang','Urumqi','urumqi',139),
('China','Xinjiang','Kashgar','kashgar',140),
('China','Tibet','Lhasa','lhasa',141),
('China','Tibet','Shigatse','shigatse',142);

